# Generated by Django 4.2.16 on 2024-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
